### ISSUE TITLE
Observability Dashboard uses fact_column.row_count instead of fact_execution.total_rowcount

### ISSUE THREAD

**Issue by ataft** [flexanalytics/dbt_observability_marts#21]
Should switch to fact_execution.total_rowcount

![image](https://github.com/user-attachments/assets/4019aebe-dd2d-4548-8a66-05700eb7d6df)

**Comment by MiConnell** [comment]
This has been updated on all dashboards and in the template repo, please review and I can close out after approval

**Comment by ataft** [comment]
There's still a filter on fact_column.row_count

![image](https://github.com/user-attachments/assets/d2a2adc8-ae65-454f-9415-3aff2d7780b4)

**Comment by MiConnell** [comment]
Filters have been removed from all dashboards and the template repo
